name: Spotify - All Modes
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  spotify:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.music.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_limit: 7
          plugin_music_mode: combined  # enables recent + top + playlist
          plugin_music_playlist: https://open.spotify.com/embed/playlist/37i9dQZF1EIeGlWlhIHJPO  # optional
