name: WakaTime
on:
  schedule: [{ cron: "0 * * * *" }] # every hour
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_days: 180
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
